version: '3.7'
services:
  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    volumes:
      - pgadmin:/var/lib/pgadmin
  artemis:
    image: artemis:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L
    environment:
      NODE_ENV: development
    volumes:
      - ./artemis/src:/usr/app/src:ro
    # volumes:
    #   - type: bind
    #     source: ./business-logic/src/
    #     target: /usr/app/src/
    #     consistency: cached
volumes:
  postgres:
  pgadmin: