version: '3.7'
services:
  nginx:
    volumes:
      - ./public:/usr/share/nginx/html:ro
  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    volumes:
      - pgadmin:/var/lib/pgadmin
  business-logic:
    image: business-logic:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L
    environment:
      NODE_ENV: development
    volumes:
      - ./business-logic/src:/usr/app/src:ro
    # volumes:
    #   - type: bind
    #     source: ./business-logic/src/
    #     target: /usr/app/src/
    #     consistency: cached
volumes:
  postgres:
  pgadmin: