# production configuration. See docker-compose.override.yml from development specific configurations
version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - ./public:/usr/share/nginx/html:ro
  postgres:
    image: postgres:11-alpine
    restart: always
    # expose:
    #   - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.6
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2
    ports:
      - "6060:6060"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 6060
      HASURA_GRAPHQL_SERVER_HOST: graphql-engine
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_AUTH_HOOK: http://artemis:9090/api/v1/hooks/hasura/auth
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
  artemis:
    image: artemis:prod
    build:
      context: ./artemis
      args:
        NODE_ENV: production
    command: node src/index.js
    ports:
      - "9090:9090"
    restart: always
    environment:
      NODE_ENV: production
      PGHOST: postgres
      PGUSER: ${PG_USERNAME}
      PGDATABASE: ${PG_DATABASE}
      PGPASSWORD: ${PG_PASSWORD}
      PGPORT: 5432
      PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
      FILE_UPLOAD_DIRECTORY: /usr/app/uploads
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      OAUTH_PROVIDER_FACEBOOK_CLIENT_ID: ${OAUTH_PROVIDER_FACEBOOK_CLIENT_ID}
      OAUTH_PROVIDER_FACEBOOK_CLIENT_SECRET: ${OAUTH_PROVIDER_FACEBOOK_CLIENT_SECRET}
      OAUTH_PROVIDER_GOOGLE_CLIENT_ID: ${OAUTH_PROVIDER_GOOGLE_CLIENT_ID}
      OAUTH_PROVIDER_GOOGLE_CLIENT_SECRET: ${OAUTH_PROVIDER_GOOGLE_CLIENT_SECRET}
      KHIPU_CLIENT_ID: ${KHIPU_CLIENT_ID}
      KHIPU_CLIENT_SECRET: ${KHIPU_CLIENT_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./public/uploads:/usr/app/uploads:rw
