version: '3.7'
services:
  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    volumes:
      - pgadmin:/var/lib/pgadmin
  artemis:
    image: artemis:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L
    environment:
      NODE_ENV: development
    volumes:
      - ./artemis/src:/usr/app/src
      - ./node_modules:/usr/app/src/node_modules
  hermes:
    image: hermes:dev
    build:
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
    volumes:
      - ./hermes/src:/usr/app/src
      - ./node_modules:/usr/app/src/node_modules
  # hades:
  #   image: hades:dev
  #   build:
  #     args:
  #       NODE_ENV: development
  #   environment:
  #     NODE_ENV: development
  #   environment:
  #     NODE_ENV: development
volumes:
  postgres:
  pgadmin: