DROP SCHEMA webstore CASCADE;
DROP SCHEMA website CASCADE;
DROP SCHEMA accounting CASCADE;
DROP SCHEMA calendar CASCADE;
DROP SCHEMA i18n CASCADE;
DROP SCHEMA account CASCADE;
DROP FUNCTION set_updated_at;